language: php
sudo: false
php:
- 7.1
- 7.2

before_install:
- composer self-update

install:
- travis_retry composer install --no-interaction --prefer-source

script:
- vendor/bin/kahlan --clover=build/logs/clover.xml

after_success:
- travis_retry php vendor/bin/php-coveralls -v
